### ISSUE TITLE
Homework 2

### ISSUE THREAD

**Issue by pistriak** [koldmit/GeekHubHomeworks#1]
1. Classes Circle, Rectangle, Square and Triangle should not contain any input/output logic;
   All input/output logic should be in Main class; 
   Classes like Circle should be very simple, like this:

```

public class Circle implements Shape {

    private double radius;

    public Circle(double radius) {
        this.radius = radius;
    }

    @Override
    public double calculateArea() {
        return Math.PI * Math.pow(radius, 2);
    }

    @Override
    public double calculatePerimeter() {
        return 2 * Math.PI * radius;
    }
}
```
1. You don't need ShapesFabric in out case;

**Comment by koldmit** [comment]
My system is ruined :)  I thought is was elegant and independent from Main class. Maybe it is more Delphi style. I use to write form classes to promt and show data. Java web style has differences in architecture. It'll be reworked it till night.

**Comment by koldmit** [comment]
Done.
But I notice that previous solution I like more. Independent factory of shapes that takes type of object and return fully initialized object. Of cause in future this model should be splitted in data objects and interface objects. But it is weekly homework, so I tried not to complicate it too much.
