### ISSUE TITLE
Homework 3

### ISSUE THREAD

**Issue by pistriak** [koldmit/GeekHubHomeworks#2]
1. Package names should be in lowercase. Store -> store;
2. Code is not formatted properly; `abstract public class Bike extends Product{` -> `abstract public class Bike extends Product {`;
3.  `abstract public class Bike` ->  `public abstract class Bike` in Cyclocross.java;
4. Not needed: `public static final boolean isBestBikeTypeEver = true;`;
5. Delete comment `//to calc our profit when sell by price of product` in Lot.java;
6. Use StringBuilder instead of StringBuffer;
7. Don't include 'List' in method names if method doesn't return a List; (BikeStore.getListOfProdLot);
8. I would return a list of products in this method BikeStore.getListOfProducts; 
List<Product> getAllProducts(); 
If the there are no products just return empty list. (Collections.emptyList());
9. Don't use short names for public methods 
`    public Product getProdByName(String name)` -> `getProductByName`
10. String getListOfProdLot (Product prod) ->` List<Lot>getLotsForProduct(Product product)`;
 11. Then create some class witch takes products and lots and prints them to console. 
12. `public double getCostOfProd(String prodName)` -> getCostOfProduct(String productName)

**Comment by koldmit** [comment]
Done.
I don't need StringBuilder with new output class for list and map now, because write data dirrectly to console. But I read differences between StringBuilder and StringBuffer and remember them.
